'use client';

import { useState } from 'react';

export default function PDFExport({ itinerary, destination }) {
  const [exporting, setExporting] = useState(false);

  const handleExport = async () => {
    setExporting(true);
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

      const pageW = doc.internal.pageSize.getWidth();
      const pageH = doc.internal.pageSize.getHeight();
      const margin = 16;
      const usableW = pageW - margin * 2;
      let y = margin;

      const checkPage = (needed = 10) => {
        if (y + needed > pageH - margin) {
          doc.addPage();
          y = margin;
        }
      };

      const writeText = (text, x, fontSize, color, bold = false, maxW = usableW) => {
        doc.setFontSize(fontSize);
        doc.setTextColor(...color);
        doc.setFont('helvetica', bold ? 'bold' : 'normal');
        const lines = doc.splitTextToSize(String(text || ''), maxW);
        checkPage(lines.length * (fontSize * 0.4 + 1));
        doc.text(lines, x, y);
        y += lines.length * (fontSize * 0.4 + 1);
      };

      // ── Header ──────────────────────────────────────────────────────────────
      doc.setFillColor(15, 118, 110); // teal-700
      doc.rect(0, 0, pageW, 28, 'F');
      doc.setFontSize(20);
      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
      doc.text(itinerary.destination || destination, margin, 12);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.text(`${itinerary.totalDays}-Day ${itinerary.travelStyle || 'Balanced'} Itinerary  ·  Generated by Journeo`, margin, 20);
      y = 36;

      // ── Overview ────────────────────────────────────────────────────────────
      if (itinerary.overview) {
        writeText(itinerary.overview, margin, 9, [148, 163, 184]);
        y += 3;
      }

      // ── Trip Info pills ──────────────────────────────────────────────────────
      const pills = [
        itinerary.currency && `Currency: ${itinerary.currency}`,
        itinerary.language && `Language: ${itinerary.language}`,
        itinerary.timezone && `Timezone: ${itinerary.timezone}`,
        itinerary.climate && `Climate: ${itinerary.climate}`,
        itinerary.gettingAround && `Getting Around: ${itinerary.gettingAround}`,
      ].filter(Boolean);

      if (pills.length) {
        doc.setFillColor(30, 41, 59); // slate-800
        doc.roundedRect(margin, y, usableW, 8 + pills.length * 5.5, 2, 2, 'F');
        y += 5;
        pills.forEach((p) => {
          doc.setFontSize(8);
          doc.setTextColor(148, 163, 184);
          doc.setFont('helvetica', 'normal');
          doc.text(`• ${p}`, margin + 4, y);
          y += 5.5;
        });
        y += 4;
      }

      // ── Days ────────────────────────────────────────────────────────────────
      const days = itinerary.days || [];
      for (const day of days) {
        checkPage(20);

        // Day header bar
        doc.setFillColor(13, 148, 136); // teal-600
        doc.rect(margin, y, usableW, 8, 'F');
        doc.setFontSize(10);
        doc.setTextColor(255, 255, 255);
        doc.setFont('helvetica', 'bold');
        doc.text(`Day ${day.day}  —  ${day.theme || ''}`, margin + 3, y + 5.5);
        if (day.zone) {
          doc.setFontSize(8);
          doc.setFont('helvetica', 'normal');
          doc.text(`📍 ${day.zone}`, pageW - margin - 3, y + 5.5, { align: 'right' });
        }
        y += 10;

        // Activities
        const renderActivities = (acts, slotLabel) => {
          if (!acts?.length) return;
          writeText(slotLabel, margin, 8, [100, 116, 139], true);
          y += 1;
          acts.forEach((a) => {
            checkPage(16);
            doc.setFontSize(9);
            doc.setTextColor(226, 232, 240);
            doc.setFont('helvetica', 'bold');
            const timeStr = a.time ? `${a.time}  ` : '';
            doc.text(timeStr + (a.place || ''), margin + 4, y);
            y += 4.5;
            if (a.description) {
              const lines = doc.splitTextToSize(a.description, usableW - 8);
              doc.setFontSize(8);
              doc.setTextColor(148, 163, 184);
              doc.setFont('helvetica', 'normal');
              checkPage(lines.length * 4);
              doc.text(lines, margin + 4, y);
              y += lines.length * 4;
            }
            const meta = [a.entryFee && `Fee: ${a.entryFee}`, a.tip && `Tip: ${a.tip}`].filter(Boolean).join('  ·  ');
            if (meta) {
              doc.setFontSize(7.5);
              doc.setTextColor(94, 234, 212); // teal-300
              const mLines = doc.splitTextToSize(meta, usableW - 8);
              checkPage(mLines.length * 3.5);
              doc.text(mLines, margin + 4, y);
              y += mLines.length * 3.5 + 2;
            }
          });
          y += 2;
        };

        renderActivities(day.morning, 'Morning');
        if (day.lunch) {
          writeText(`Lunch: ${day.lunch}`, margin, 8, [52, 211, 153], false);
          y += 2;
        }
        renderActivities(day.afternoon, 'Afternoon');
        if (day.dinner) {
          writeText(`Dinner: ${day.dinner}`, margin, 8, [52, 211, 153], false);
          y += 2;
        }
        renderActivities(day.evening, 'Evening');

        // Day footer
        const footerParts = [
          day.accommodation && `🏨 ${day.accommodation}`,
          day.estimatedCost && `💰 ${day.estimatedCost}`,
          day.transport && `🚌 ${day.transport}`,
        ].filter(Boolean);
        if (footerParts.length) {
          footerParts.forEach((f) => {
            writeText(f, margin, 8, [100, 116, 139]);
          });
        }
        y += 6;
      }

      // ── Tips & Must-Try ─────────────────────────────────────────────────────
      checkPage(20);
      writeText('General Tips', margin, 11, [20, 184, 166], true);
      y += 2;
      (itinerary.generalTips || []).forEach((t) => {
        writeText(`• ${t}`, margin, 8.5, [148, 163, 184]);
      });

      y += 4;
      checkPage(20);
      writeText('Must Try', margin, 11, [20, 184, 166], true);
      y += 2;
      (itinerary.mustTry || []).forEach((t) => {
        writeText(`• ${t}`, margin, 8.5, [148, 163, 184]);
      });

      // ── Footer on all pages ──────────────────────────────────────────────────
      const totalPages = doc.getNumberOfPages();
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(7);
        doc.setTextColor(71, 85, 105);
        doc.text(`Journeo  ·  Page ${i} of ${totalPages}`, pageW / 2, pageH - 6, { align: 'center' });
      }

      doc.save(`${destination.replace(/\s+/g, '_')}_itinerary.pdf`);
    } catch (err) {
      console.error('PDF export failed:', err);
      alert('PDF export failed. Please try again.');
    } finally {
      setExporting(false);
    }
  };

  return (
    <button
      onClick={handleExport}
      disabled={exporting}
      className="flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-lg border border-slate-700 bg-slate-800/80 text-slate-400 hover:text-slate-200 hover:border-slate-500 transition-all disabled:opacity-50"
    >
      <span>{exporting ? '⏳' : '📄'}</span>
      <span>{exporting ? 'Exporting...' : 'Export PDF'}</span>
    </button>
  );
}
