'use client';

import { useState } from 'react';

export default function PDFExport({ itinerary, destination }) {
  const [exporting, setExporting] = useState(false);

  const handleExport = async () => {
    setExporting(true);
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

      // ── Journeo brand palette (matches tailwind.config.js) ──────────────────
      const INK        = [15, 13, 10];
      const INK_SOFT    = [61, 58, 53];
      const INK_MUTED   = [107, 102, 93];
      const LINE        = [232, 226, 217];
      const PAPER_WARM  = [245, 240, 232];
      const SAFFRON     = [249, 115, 22];
      const SAFFRON_DEEP = [234, 88, 12];
      const JADE_DEEP   = [4, 120, 87];
      const WHITE       = [255, 255, 255];

      const pageW = doc.internal.pageSize.getWidth();
      const pageH = doc.internal.pageSize.getHeight();
      const margin = 18;
      const usableW = pageW - margin * 2;
      let y = margin;

      const checkPage = (needed = 10) => {
        if (y + needed > pageH - margin) {
          doc.addPage();
          y = margin;
        }
      };

      // Serif for headings (echoes the site's Playfair Display), sans for body.
      const setFont = (family, style = 'normal') => doc.setFont(family === 'serif' ? 'times' : 'helvetica', style);

      const writeText = (text, x, fontSize, color, { bold = false, serif = false, maxW = usableW, lineGap = 1 } = {}) => {
        doc.setFontSize(fontSize);
        doc.setTextColor(...color);
        setFont(serif ? 'serif' : 'helvetica', bold ? 'bold' : 'normal');
        const lines = doc.splitTextToSize(String(text || ''), maxW);
        checkPage(lines.length * (fontSize * 0.42 + lineGap));
        doc.text(lines, x, y);
        y += lines.length * (fontSize * 0.42 + lineGap);
        return lines.length;
      };

      const divider = (color = LINE, gapAbove = 3, gapBelow = 4) => {
        y += gapAbove;
        doc.setDrawColor(...color);
        doc.setLineWidth(0.4);
        doc.line(margin, y, pageW - margin, y);
        y += gapBelow;
      };

      const sectionHeading = (text) => {
        checkPage(14);
        doc.setFontSize(13);
        doc.setTextColor(...INK);
        setFont('serif', 'bold');
        doc.text(text, margin, y);
        const tw = doc.getTextWidth(text);
        doc.setDrawColor(...SAFFRON);
        doc.setLineWidth(1);
        doc.line(margin, y + 1.8, margin + tw, y + 1.8);
        y += 8;
      };

      const bulletList = (items, { fontSize = 9, color = INK_SOFT } = {}) => {
        items.forEach((item) => {
          checkPage(8);
          doc.setFillColor(...SAFFRON);
          doc.circle(margin + 1, y - 1.3, 0.7, 'F');
          doc.setFontSize(fontSize);
          doc.setTextColor(...color);
          setFont('helvetica', 'normal');
          const lines = doc.splitTextToSize(String(item), usableW - 5);
          checkPage(lines.length * 4.2);
          doc.text(lines, margin + 4.5, y);
          y += lines.length * 4.2 + 2;
        });
      };

      // ── Cover header ─────────────────────────────────────────────────────────
      doc.setFontSize(26);
      doc.setTextColor(...INK);
      setFont('serif', 'bold');
      doc.text(itinerary.destination || destination, margin, y + 2);
      y += 9;

      doc.setFontSize(9.5);
      doc.setTextColor(...INK_MUTED);
      setFont('helvetica', 'normal');
      doc.text(
        `${itinerary.totalDays}-DAY ${(itinerary.travelStyle || 'BALANCED').toUpperCase()} ITINERARY  ·  GENERATED BY JOURNEO`,
        margin, y
      );
      y += 8;

      if (itinerary.overview) {
        writeText(itinerary.overview, margin, 9.5, INK_SOFT, { lineGap: 1.3 });
      }
      divider();

      // ── Trip info strip ──────────────────────────────────────────────────────
      const facts = [
        itinerary.bestTimeToVisit && ['Best Time', itinerary.bestTimeToVisit],
        itinerary.currency && ['Currency', itinerary.currency],
        itinerary.language && ['Language', itinerary.language],
        itinerary.timezone && ['Timezone', itinerary.timezone],
        itinerary.climate && ['Climate', itinerary.climate],
        itinerary.gettingAround && ['Getting Around', itinerary.gettingAround],
      ].filter(Boolean);

      if (facts.length) {
        const rowH = 11;
        const boxH = facts.length * rowH + 6;
        checkPage(boxH);
        doc.setFillColor(...PAPER_WARM);
        doc.roundedRect(margin, y, usableW, boxH, 2, 2, 'F');
        let fy = y + 7;
        facts.forEach(([label, value]) => {
          doc.setFontSize(7.5);
          doc.setTextColor(...INK_MUTED);
          setFont('helvetica', 'bold');
          doc.text(label.toUpperCase(), margin + 5, fy);
          doc.setFontSize(9);
          doc.setTextColor(...INK);
          setFont('helvetica', 'normal');
          const lines = doc.splitTextToSize(String(value), usableW - 40);
          doc.text(lines, margin + 40, fy);
          fy += Math.max(rowH, lines.length * 4.2 + 4);
        });
        y += boxH + 8;
      }

      // ── Days ────────────────────────────────────────────────────────────────
      const days = itinerary.days || [];
      for (const day of days) {
        checkPage(22);

        // Day header bar
        doc.setFillColor(...SAFFRON);
        doc.rect(margin, y, usableW, 9, 'F');
        doc.setFontSize(10.5);
        doc.setTextColor(...WHITE);
        setFont('helvetica', 'bold');
        doc.text(`DAY ${day.day}`, margin + 3.5, y + 6);
        const dayNumW = doc.getTextWidth(`DAY ${day.day}`);
        setFont('helvetica', 'normal');
        doc.text(day.theme || '', margin + 3.5 + dayNumW + 3, y + 6);
        if (day.zone) {
          doc.setFontSize(8);
          doc.text(day.zone, pageW - margin - 3.5, y + 6, { align: 'right' });
        }
        y += 13;

        const renderActivities = (acts, slotLabel) => {
          if (!acts?.length) return;
          doc.setFontSize(7.5);
          doc.setTextColor(...JADE_DEEP);
          setFont('helvetica', 'bold');
          doc.text(slotLabel.toUpperCase(), margin, y);
          y += 5;
          acts.forEach((a) => {
            checkPage(16);
            doc.setFontSize(9.5);
            doc.setTextColor(...INK);
            setFont('helvetica', 'bold');
            const timeStr = a.time ? `${a.time}` : '';
            doc.text(timeStr, margin, y);
            const timeW = timeStr ? doc.getTextWidth(timeStr) + 4 : 0;
            doc.text(a.place || '', margin + timeW, y);
            y += 4.8;
            if (a.description) {
              const lines = doc.splitTextToSize(a.description, usableW - 4);
              doc.setFontSize(8.5);
              doc.setTextColor(...INK_SOFT);
              setFont('helvetica', 'normal');
              checkPage(lines.length * 4);
              doc.text(lines, margin + 4, y);
              y += lines.length * 4;
            }
            const metaParts = [
              a.entryFee && `Fee: ${a.entryFee}`,
              a.tip && `Tip: ${a.tip}`,
            ].filter(Boolean);
            if (metaParts.length) {
              const meta = metaParts.join('   ·   ');
              doc.setFontSize(8);
              doc.setTextColor(...SAFFRON_DEEP);
              setFont('helvetica', 'italic');
              const mLines = doc.splitTextToSize(meta, usableW - 4);
              checkPage(mLines.length * 3.8);
              doc.text(mLines, margin + 4, y);
              y += mLines.length * 3.8 + 1;
            }
            y += 2;
          });
          y += 1;
        };

        const renderMeal = (label, value) => {
          if (!value) return;
          checkPage(7);
          doc.setFontSize(7.5);
          doc.setTextColor(...WHITE);
          setFont('helvetica', 'bold');
          const labelW = doc.getTextWidth(label) + 4;
          doc.setFillColor(...JADE_DEEP);
          doc.roundedRect(margin, y - 3.6, labelW, 4.8, 1, 1, 'F');
          doc.text(label, margin + 2, y);
          doc.setFontSize(8.5);
          doc.setTextColor(...INK_SOFT);
          setFont('helvetica', 'normal');
          const lines = doc.splitTextToSize(value, usableW - labelW - 4);
          doc.text(lines, margin + labelW + 3, y);
          y += Math.max(4.8, lines.length * 4) + 3;
        };

        renderActivities(day.morning, 'Morning');
        renderMeal('LUNCH', day.lunch);
        renderActivities(day.afternoon, 'Afternoon');
        renderMeal('DINNER', day.dinner);
        renderActivities(day.evening, 'Evening');

        // Day footer
        const footerParts = [
          day.accommodation && `Stay: ${day.accommodation}`,
          day.estimatedCost && `Cost: ${day.estimatedCost}`,
          day.transport && `Transport: ${day.transport}`,
        ].filter(Boolean);
        if (footerParts.length) {
          checkPage(footerParts.length * 4.2 + 2);
          doc.setDrawColor(...LINE);
          doc.setLineWidth(0.3);
          doc.line(margin, y, pageW - margin, y);
          y += 4;
          footerParts.forEach((f) => {
            writeText(f, margin, 8, INK_MUTED, { lineGap: 0.6 });
          });
        }
        y += 6;
      }

      // ── Tips, Must-Try, Avoid ────────────────────────────────────────────────
      if (itinerary.generalTips?.length) {
        checkPage(20);
        sectionHeading('General Tips');
        bulletList(itinerary.generalTips);
        y += 3;
      }

      if (itinerary.mustTry?.length) {
        checkPage(20);
        sectionHeading('Must Try');
        bulletList(itinerary.mustTry);
        y += 3;
      }

      if (itinerary.avoidList?.length) {
        checkPage(20);
        sectionHeading('Avoid');
        bulletList(itinerary.avoidList);
      }

      // ── Footer on all pages ──────────────────────────────────────────────────
      const totalPages = doc.getNumberOfPages();
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setDrawColor(...LINE);
        doc.setLineWidth(0.3);
        doc.line(margin, pageH - 12, pageW - margin, pageH - 12);
        doc.setFontSize(7.5);
        doc.setTextColor(...INK_MUTED);
        setFont('helvetica', 'normal');
        doc.text('JOURNEO', margin, pageH - 7);
        doc.text(`Page ${i} of ${totalPages}`, pageW - margin, pageH - 7, { align: 'right' });
      }

      doc.save(`${destination.replace(/\s+/g, '_')}_itinerary.pdf`);
    } catch (err) {
      console.error('PDF export failed:', err);
      alert('PDF export failed. Please try again.');
    } finally {
      setExporting(false);
    }
  };

  return (
    <button
      onClick={handleExport}
      disabled={exporting}
      className="flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-lg border border-slate-700 bg-slate-800/80 text-slate-400 hover:text-slate-200 hover:border-slate-500 transition-all disabled:opacity-50"
    >
      <span>{exporting ? '⏳' : '📄'}</span>
      <span>{exporting ? 'Exporting...' : 'Export PDF'}</span>
    </button>
  );
}
