import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service | Journeo',
  description: 'Terms and conditions for using Journeo.',
};

const LAST_UPDATED = 'April 19, 2026';
const CONTACT_EMAIL = 'legal@journeo.com';
const APP_NAME = 'Journeo';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-950">
      {/* Header */}
      <header className="border-b border-slate-800 bg-slate-950/90 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-4 py-3.5 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-teal-500 to-teal-700 flex items-center justify-center text-base shadow-lg shadow-teal-900/30">
              ✈️
            </div>
            <span className="text-lg font-bold text-slate-100">Journeo</span>
          </Link>
          <Link href="/" className="text-sm text-slate-400 hover:text-teal-400 transition-colors">
            ← Back to Home
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-12">
        <div className="mb-10">
          <p className="text-xs text-teal-400 font-semibold uppercase tracking-widest mb-2">Legal</p>
          <h1 className="text-3xl font-extrabold text-slate-100 mb-3">Terms of Service</h1>
          <p className="text-sm text-slate-500">Last updated: {LAST_UPDATED}</p>
        </div>

        <div className="space-y-8">

          <Section title="1. Acceptance of Terms">
            <p>By using {APP_NAME} ("Service"), you agree to these Terms. If you don't agree, please don't use the Service. We may update these Terms — continued use means acceptance.</p>
          </Section>

          <Section title="2. The Service">
            <p>{APP_NAME} provides AI-generated travel itineraries and related features including collaboration, Travel Buddy matching, and travel information. The Service is provided "as is". AI-generated content may contain errors — always verify travel details independently before booking.</p>
          </Section>

          <Section title="3. Your Account">
            <ul>
              <li>You must be at least 13 years old to create an account.</li>
              <li>You're responsible for keeping your password secure. Don't share account credentials.</li>
              <li>You're responsible for all activity that occurs under your account.</li>
              <li>We reserve the right to suspend accounts that violate these Terms.</li>
            </ul>
          </Section>

          <Section title="4. Acceptable Use">
            <p className="mb-3">You agree not to:</p>
            <ul>
              <li>Use the Service to harass, threaten, or harm other users</li>
              <li>Post false, misleading, or spam content in Travel Buddy profiles or trip chats</li>
              <li>Attempt to scrape, reverse-engineer, or overload our servers</li>
              <li>Use automated tools to create fake accounts or listings</li>
              <li>Impersonate other people or organisations</li>
            </ul>
          </Section>

          <Section title="5. Travel Buddy Feature">
            <p>The Travel Buddy feature is opt-in. By opting in, you understand:</p>
            <ul>
              <li>Your first name, travel style, and trip dates will be visible to other users</li>
              <li>Your email is only shared when you accept a connection request</li>
              <li>We are not responsible for interactions between users that occur outside the platform</li>
              <li>Exercise normal personal safety precautions when meeting people you've connected with online</li>
              <li>You can opt out and remove your listing at any time</li>
            </ul>
          </Section>

          <Section title="6. AI-Generated Content">
            <p>Itineraries are generated by AI and may contain inaccuracies, outdated information, or errors. {APP_NAME} is not liable for:</p>
            <ul>
              <li>Incorrect opening hours, prices, or availability of attractions</li>
              <li>Safety conditions at recommended locations</li>
              <li>Visa, entry, or travel requirement information</li>
              <li>Any losses arising from reliance on AI-generated content</li>
            </ul>
            <p className="mt-3">Always verify travel information with official sources before booking.</p>
          </Section>

          <Section title="7. Intellectual Property">
            <p>The {APP_NAME} platform, including its design, code, and branding, is owned by us. You retain ownership of content you create (trip notes, suggestions, messages). By using the Service, you grant us a limited licence to display and process your content to provide the Service.</p>
          </Section>

          <Section title="8. Limitation of Liability">
            <p>To the maximum extent permitted by law, {APP_NAME} is not liable for any indirect, incidental, or consequential damages arising from your use of the Service. Our total liability in any case shall not exceed the amount you paid us in the 12 months prior to the claim (if any).</p>
          </Section>

          <Section title="9. Termination">
            <p>You may stop using the Service at any time. We may terminate or suspend your account if you violate these Terms. Upon termination, your right to use the Service ceases, but provisions regarding liability and IP survive.</p>
          </Section>

          <Section title="10. Governing Law">
            <p>These Terms are governed by applicable law. Any disputes shall be resolved through good-faith negotiation first, then binding arbitration if needed. Contact us at <a href={`mailto:${CONTACT_EMAIL}`} className="text-teal-400 hover:text-teal-300">{CONTACT_EMAIL}</a>.</p>
          </Section>

          <Section title="11. Contact">
            <p>Questions about these Terms? Email <a href={`mailto:${CONTACT_EMAIL}`} className="text-teal-400 hover:text-teal-300">{CONTACT_EMAIL}</a></p>
          </Section>

        </div>

        <div className="mt-12 pt-8 border-t border-slate-800 flex flex-wrap gap-4 text-sm text-slate-500">
          <Link href="/privacy" className="hover:text-teal-400 transition-colors">Privacy Policy</Link>
          <Link href="/" className="hover:text-teal-400 transition-colors">← Back to Journeo</Link>
        </div>
      </main>
    </div>
  );
}

function Section({ title, children }) {
  return (
    <div className="bg-slate-900/40 border border-slate-800 rounded-2xl p-6">
      <h2 className="text-base font-bold text-slate-100 mb-4">{title}</h2>
      <div className="text-sm text-slate-400 leading-relaxed space-y-2 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1.5 [&_a]:text-teal-400 [&_a:hover]:text-teal-300">
        {children}
      </div>
    </div>
  );
}
